spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itemsharingdatabase
    username: root
    password: root
  application:
    name: itemservice
  zipkin:
    base-url: http://localhost:9411

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user
    client:
      client-id: webclient

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG