spring:
  application:
    name: zuulservice
  profiles:
    active:
    - default
  zipkin:
    base-url: http://localhost:9411

security:
  basic:
    enabled: false

server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    authorizationservice:
      path: /oauth/**
      url: http://localhost:8901/oauth
    userservice: /user/**
    itemservice: /item/**
  ignored-services: '*'
  prefix: /api
  sensitive-headers: Cookie, Set-Cookie
  host:
    connect-timeout-millis: 12000
    socket-timeout-millis: 12000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG